name: "Docker"

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: jaredallard/akkoma

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set build environment environment variables
        run: |-
          echo "AKKOMA_VERSION=$(cat .akkoma_version)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
      - name: Build and push image
        uses: docker/build-push-action@v6
        id: push
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
        with:
          context: .
          push: true
          sbom: true
          # TODO(jaredallard): Enable linux/arm64 later.
          platforms: linux/amd64
          build-args: |
            VCS_REF=${{ env.AKKOMA_VERSION}}
            BUILD_DATE=${{ env.BUILD_DATE}}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.AKKOMA_VERSION }}
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
